version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - run:
          name: Plan a release
          command: circleci run release plan --target-version='v1.2.3'
      - run:
          name: Update a release
          command: circleci run release update --status=SUCCESS

workflows:
  my-workflow:
    jobs:
      - hello-job
