version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - run: uuid=$(uuidgen)
      - run: echo $uuid
      - run:
          name: Plan a release
          command: circleci run release plan --target-version=<$uuid>
      - run:
          name: Update a release
          command: circleci run release update --status=SUCCESS

workflows:
  my-workflow:
    jobs:
      - hello-job
